CREATE TABLE pokemon_data_table (

pokedex_number INT NOTNULL,
english_name VARCHAR NOTNULL,
german_name VARCHAR NOTNULL,
japanese_name VARCHAR NOTNULL,
generation INT NOTNULL,
status VARCHAR NOTNULL,
species VARCHAR NOTNULL,
type_number INT NOTNULL,
type_1 VARCHAR NOTNULL,
type_2 VARCHAR NOTNULL,
height_m REAL NOTNULL,
weight_kg REAL NOTNULL,
abilities_number INT NOTNULL,
ability_1 VARCHAR NOTNULL,
ability_2 VARCHAR NOTNULL,
ability_hidden VARCHAR NOTNULL,
total_points REAL NOTNULL,
hp REAL NOTNULL,
attack REAL NOTNULL,
defense REAL NOTNULL,
sp_attack REAL NOTNULL,
sp_defense REAL NOTNULL,
speed REAL NOTNULL,
catch_rate REAL NOTNULL,
base_friendship REAL NOTNULL,
base_experience REAL NOTNULL,
growth_rate VARCHAR NOTNULL,
egg_type_number INT NOTNULL,
egg_type_1 VARCHAR NOTNULL,
egg_type_2 VARCHAR NOTNULL,
percentage_male REAL NOTNULL,
egg_cycles REAL NOTNULL,
against_normal REAL NOTNULL,
against_fire REAL NOTNULL,
against_water REAL NOTNULL,
against_electric REAL NOTNULL,
against_grass REAL NOTNULL,
against_ice REAL NOTNULL,
against_fight REAL NOTNULL,
against_poison REAL NOTNULL,
against_ground REAL NOTNULL,
against_flying REAL NOTNULL,
against_psychic REAL NOTNULL,
against_bug REAL NOTNULL,
against_rock REAL NOTNULL,
against_ghost REAL NOTNULL,
against_dragon REAL NOTNULL,
against_dark REAL NOTNULL,
against_steel REAL NOTNULL,
against_fairy REAL NOTNULL,
	
    PRIMARY KEY (pokedex_number),
	UNIQUE (english_name)
);